### PR TITLE
PKG: move `inflection` package from requirements.txt

### PR DESCRIPTION
**Pull request by mrakitin**
We don't have `requirements-dev.txt` file in this repo, so I moved it to the best match `requirements-test.txt`.

Closes https://github.com/bluesky/ophyd/issues/1011.

### CODE REVIEW

**Review by jwlodek — APPROVED** [review]

**Review by dmgav — APPROVED** [review]

**Comment by mrakitin** [comment]
> I would be fine with this change but, on inspection, cannot find where `inflection` is used in `ophyd`. It's in `scripts/collect_ad_boilerplate.py` but that is a suggestion for code to be used, isn't it? It is not a unit test.
> 
> So, I can't approve yet.

Yes, it's used in https://github.com/bluesky/ophyd/blob/dd4b3e389a0202ecacce39fc3965d703c616b0d4/scripts/collect_ad_boilerplate.py#L5 and I mistakenly guided @jwlodek to put the dependency into the `requirements.txt` rather than in a separate place while he was working on https://github.com/bluesky/ophyd/pull/975.

@prjemian, what would be your suggestions? Another `requirements-dev.txt` file with that single dependency? I don't think it should stay in `requirements.txt`...

**Comment by prjemian** [comment]
How is file `scripts/collect_ad_boilerplate.py` used?  Looks as if it is an example.  If that is the case, it is either a conditional requirements for `scripts` or additional documentation in this file.  As it stands, it is not necessary for use or testing of `ophyd`.

**Comment by jwlodek** [comment]
The script is used to auto-create ophyd classes for areaDetector drivers by scraping their `*.template` files. I wrote it mostly because I was writing classes for the `ADPICam` driver and it had over 200 PVs, so it felt like it made sense to just automate the process. I've used it to add a few other detector classes since then as well.

**Comment by prjemian** [comment]
@jwlodek That's a good addition for the [docstring](https://github.com/bluesky/ophyd/blob/dd4b3e389a0202ecacce39fc3965d703c616b0d4/scripts/collect_ad_boilerplate.py#L11).

This seems a justification for inclusion in `requirements-dev.txt`

**Comment by prjemian** [comment]
revised doc string

```python
    Writes boilerplate 'Detector' class for ophyd/areadetector/detectors.

    This script is automates the creation of ophyd classes for areaDetector drivers by scraping
    their *.template files. It is called by developers as needed.
```

**Review by ZLLentz — APPROVED** [review]
I agree with @prjemian that `requirements-dev.txt` would be most appropriate, but I'm just happy to see it removed from `requirements.txt` to make the setup.py requirements list accurate again.

**Comment by mrakitin** [comment]
I moved `inflection` to `requirements-dev.txt` (new file) and updated the docstring as discussed. @prjemian, @ZLLentz, are you OK with that outcome?

**Review by prjemian — APPROVED** [review]
LGTM, Thanks!

**Review by jwlodek — APPROVED** [review]

**Comment by mrakitin** [comment]
Neat! @ZLLentz, you have the honor of merging it then 😄.

**Pull request merged**
