### PR TITLE
DOC: release notes for v1.8.0

### PR DESCRIPTION
**Pull request by mrakitin**
Here are the relevant updates which will be added to the release description (auto-generated by GitHub).

## What's Changed
* add support for EPICS area detector pvaDriver cam by @prjemian in https://github.com/bluesky/ophyd/pull/1055
* Adopt isort by @coretl in https://github.com/bluesky/ophyd/pull/1064
* Make SynAxis produce an updating MoveStatus by @callumforrester in https://github.com/bluesky/ophyd/pull/1036
* Fix capture signal was always triggered by @physwkim in https://github.com/bluesky/ophyd/pull/1066
* Move settings to setup.cfg and use setuptools-scm by @coretl in https://github.com/bluesky/ophyd/pull/1065
* Fix SynAxisNoPosition by @coretl in https://github.com/bluesky/ophyd/pull/1068
* Add v2 dir by @coretl in https://github.com/bluesky/ophyd/pull/1067
* Make CI run on external PRs by @coretl in https://github.com/bluesky/ophyd/pull/1071
* Use pydata docs theme and make a space for v2 docs by @coretl in https://github.com/bluesky/ophyd/pull/1076
* Deploy to the correct place by @coretl in https://github.com/bluesky/ophyd/pull/1077
* DOC: fixed minor typo. by @clintonroy in https://github.com/bluesky/ophyd/pull/1079
* DOC: minor typo fix. by @clintonroy in https://github.com/bluesky/ophyd/pull/1080
* DOC: added a shutter example of a PVPositionerComparator by @clintonroy in https://github.com/bluesky/ophyd/pull/1081
* Update LICENSE by @stuartcampbell in https://github.com/bluesky/ophyd/pull/1082
* Ophyd v2 core by @coretl in https://github.com/bluesky/ophyd/pull/1078
* Fix docs linking by @coretl in https://github.com/bluesky/ophyd/pull/1085
* Change `make_dir_tree` default dir mode to `755` by @mrakitin in https://github.com/bluesky/ophyd/pull/1087
* Add status repr to WaitTimeoutError message by @dperl-dls in https://github.com/bluesky/ophyd/pull/1088
* DOC: fix install instructions in README by @mrakitin in https://github.com/bluesky/ophyd/pull/1089
* BUG: Let channelsim work with enums by @tizayi in https://github.com/bluesky/ophyd/pull/1093
* ENH: Add enum descriptor support to ChannelCa by @tizayi in https://github.com/bluesky/ophyd/pull/1097
* BUG: isinstance calls property success before status object is done by @tizayi in https://github.com/bluesky/ophyd/pull/1099
* v2: try to fix some constantly failing tests by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1105
* Ophyd v2: add _exception to AsyncStatus to propagate errors through FailedStatus. by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1103
* v2: Add dict support by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1104
* propagate errors through wait_for_connection by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1109
* Initial p4p channel implementation by @ajgdls in https://github.com/bluesky/ophyd/pull/1096
* v2: Make sim signal source look like real source by @coretl in https://github.com/bluesky/ophyd/pull/1111
* v2: make device class concrete by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1107
* v2: Added bool support for 2 element CA/PVA enums by @coretl in https://github.com/bluesky/ophyd/pull/1112
* V2 minor async status changes by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1110
* v2 Fix traceback of a failed AsyncStatus object by @coretl in https://github.com/bluesky/ophyd/pull/1114
* v2: remove monitor by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1125
* v2: Make stage/unstage async by @coretl in https://github.com/bluesky/ophyd/pull/1123
* v2: Add set_and_wait_for_value() by @coretl in https://github.com/bluesky/ophyd/pull/1124
* Let SimSignalBackend accept npt.NDArray datatypes by @RAYemelyanova in https://github.com/bluesky/ophyd/pull/1118

## New Contributors
* @physwkim made their first contribution in https://github.com/bluesky/ophyd/pull/1066
* @stuartcampbell made their first contribution in https://github.com/bluesky/ophyd/pull/1082
* @dperl-dls made their first contribution in https://github.com/bluesky/ophyd/pull/1088
* @tizayi made their first contribution in https://github.com/bluesky/ophyd/pull/1093
* @RAYemelyanova made their first contribution in https://github.com/bluesky/ophyd/pull/1105
* @ajgdls made their first contribution in https://github.com/bluesky/ophyd/pull/1096

**Full Changelog**: https://github.com/bluesky/ophyd/compare/v1.7.0...v1.8.0

### CODE REVIEW

**Comment by coretl** [comment]
Hmm, docs aren't building, I'll take a look

**Comment by coretl** [comment]
Looks like latest event-model is incompatible with ophyd, fix here: https://github.com/bluesky/event-model/pull/275

**Review by coretl — APPROVED** [review]
A new release of event model sorted the problem, so I think this is good to go

**Comment by mrakitin** [comment]
@coretl, thanks for your review and help with resolving the CI issues!

@prjemian, do you have any feedback on this PR?

**Comment by prjemian** [comment]
Aack!  My feedback is that we missed a typo in PR #1055: https://github.com/bluesky/ophyd/blob/574b4014bc843c65a593317f572dac580fae338a/ophyd/areadetector/cam.py#L43-L44

Line 44 should read `PvaDetectorCam` as written here: https://github.com/bluesky/ophyd/blob/574b4014bc843c65a593317f572dac580fae338a/ophyd/areadetector/cam.py#L1219

**Comment by prjemian** [comment]
I'll push that through in a new PR.

**Review by prjemian — APPROVED** [review]
LGTM

**Comment by mrakitin** [comment]
The release is out, thanks all!
https://pypi.org/project/ophyd/1.8.0/

**Pull request merged**
