### PR TITLE
use provided value of trigger_value

### LINKED ISSUE #1218: Provided value of trigger_value is ignored
The [docstring](https://github.com/bluesky/ophyd/blob/5df3f5694f5c4c0ac049f0e601512f220e85744b/ophyd/device.py#L139-L141) in the `Device` code says a Component maybe marked as the Signal to use from the `.trigger()` method by setting the Component's `trigger_value` kwarg.

When it comes time to actually use that signal, the provided value is ignored and a `1` is sent: https://github.com/bluesky/ophyd/blob/5df3f5694f5c4c0ac049f0e601512f220e85744b/ophyd/device.py#L1460

From https://github.com/aps-8id-dys/bluesky/issues/99

### PR DESCRIPTION
**Pull request by prjemian**
- close #1218

Tested identical change locally at APS as part of https://github.com/aps-8id-dys/bluesky/issues/95 and https://github.com/aps-8id-dys/bluesky/issues/99.

### CODE REVIEW

**Comment by prjemian** [comment]
How easy is it to create triggerable Signal that requires a testable value?  test matrix should include `1`, `"1!"` (since that is our case, and maybe some other type (maybe `bool`?).

**Comment by prjemian** [comment]
Probably want it to appear in the documentation, too.  This is a great feature and it required some investigation to uncover this capability.

**Comment by prjemian** [comment]
Document a Device's `trigger_value` kwarg in a separate issue.

**Comment by prjemian** [comment]
CI failure (in one Py3.11 configuration) does not look related to this work:

```py
/home/runner/work/_temp/351d6ed9-ee3e-433a-adbc-efc7e5388f9b.sh: line 1:  3115 Segmentation fault      (core dumped) pytest -k "${TEST_CL}"
ophyd/tests/test_areadetector.py 
```

**Comment by prjemian** [comment]
Kept re-running that test configuration until it passed.

**Review by tacaswell — APPROVED** [review]

**Pull request merged**
