### PR TITLE
add support for EPICS area detector pvaDriver cam

### LINKED ISSUE #1054: cam class for EPICS area detector pvaDriver
The [pvaDriver](https://github.com/areaDetector/pvaDriver) is an EPICS area detector camera that gets its image frame(s) from a a PV via PVAccess.  There is no `ophyd` support for this cam.

### PR DESCRIPTION
**Pull request by prjemian**
- close #1054

https://github.com/areaDetector/pvaDriver

### CODE REVIEW

**Comment by prjemian** [comment]
The [CI failure](https://github.com/bluesky/ophyd/runs/7365696078?check_suite_focus=true) is not due to these changes:

```
FAILED ophyd/tests/test_log.py::test_validate_level[pyepics] - Failed: DID NO...
= 1 failed, 1747 passed, 124 skipped, 1873 deselected, 1 xfailed, 3 warnings in 337.31s (0:05:37) =
Error: Process completed with exit code 1.
```

**Comment by prjemian** [comment]
@tacaswell Can you review or reassign?  Thanks!

**Comment by prjemian** [comment]
@jklynch Can you review?

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Can you rebase to pick up the TRACE related fix?

**Comment by prjemian** [comment]
Will do

**Comment by prjemian** [comment]
Not a frequent `rebase` user, sought [advice](https://www.w3docs.com/snippets/git/how-to-rebase-git-branch.html), here's the commands:

```bash
git checkout master
git fetch
git pull
git checkout 1054-pvaDriver-cam
git rebase origin/master
git push --force-with-lease origin HEAD
```

**Comment by prjemian** [comment]
Not sure the Py3.8 test failure is due to this code, will re-run, here's how it ends:

```
Thread 0x00007f3d8960a740 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/epics/ca.py", line 1150 in clear_channel
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/epics/ca.py", line 583 in wrapper
  File "/home/runner/work/ophyd/ophyd/ophyd/_pyepics_shim.py", line 131 in release_pvs
  File "/home/runner/work/ophyd/ophyd/ophyd/signal.py", line 898 in finalize
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/weakref.py", line 566 in __call__
  File "/home/runner/work/ophyd/ophyd/ophyd/signal.py", line 904 in destroy
  File "/home/runner/work/ophyd/ophyd/ophyd/tests/conftest.py", line 86 in ad_prefix
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/_pytest/fixtures.py", line 891 in call_fixture_func
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/_pytest/fixtures.py", line 1118 in pytest_fixture_setup
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/_pytest/logging.py", line 719 in pytest_runtest_call
/home/runner/work/_temp/8a9ed9c6-5a83-4048-b1a1-66519d407bd5.sh: line 2:  4598 Segmentation fault      (core dumped) coverage run --concurrency=thread --parallel-mode -m pytest -v -k "${TEST_CL}"
ophyd/tests/test_areadetector.py::test_basic[pyepics] 
Error: Process completed with exit code 139.
```

**Comment by prjemian** [comment]
@tacaswell Thanks.  One more rebase and pivots from `ADComponent` -> `ADCpt`,  `EpicsSignalWithRBV` -> `SignalWithRBV`, and unit test all pass.

**Pull request merged**
