### PR TITLE
Clarity how set_default_timeout interacts with inheritance.

### LINKED ISSUE #917: EpicsSignal default timeout only applies to class it's called on
https://github.com/bluesky/ophyd/blob/e168aea65213cd39bc5266c7b26da7a1c686463d/ophyd/signal.py#L851-L852

Implementation implies that it be run on `EpicsSignalBase`
However, users are reportedly running it on `EpicsSignal`, which means `EpicsSignalRO` retains the defaults.

### PR DESCRIPTION
**Pull request by danielballan**
Closes #917

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]
Looks good, nice clarification!

**Review by prjemian — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
CI (travis-ci) fails on Python: 3.7 for flake8 - whitespace

**Comment by danielballan** [comment]
Force-pushed

**Pull request merged**
