### PR TITLE
ENH: docs helper for ophyd components

### PR DESCRIPTION
**Pull request by klauer**
Upstreaming from pcdsdevices, producing component documentation like:

https://pcdshub.github.io/pcdsdevices/v2.11.0/generated/generated/pcdsdevices.attenuator.AttenuatorCalculator_AT2L0.html#pcdsdevices.attenuator.AttenuatorCalculator_AT2L0

Mirrors general implementation layout from caproto https://github.com/caproto/caproto/pull/657

(WIP as this breaks ophyd documentation. If I don't find free time to finish this, I'll likely fall back to not using this in ophyd docs just supplying it for downstream projects.)

### CODE REVIEW

**Comment by danielballan** [comment]
Wow, thanks, @klauer!

**Comment by klauer** [comment]
Generally this looks _okay_ for ophyd itself:

image
`(...clipped...)`
image

It does produce _many_ warnings which will fail the build when `-W` is in `SPHINXOPTS`. I'll leave it up to others as to whether that's an acceptable tradeoff to have this information in the docs.

**Comment by klauer** [comment]
I'll remove the ophyd documentation modifications stuff from this PR, merge, and make this viable for downstream packages.

Cleaning/fixing ophyd docs will be an exercise for the reader (_is there anybody out there? just nod if you can hear me..._).

**Comment by prjemian** [comment]
@klauer:  While you are at it, can you figure out how to get the [viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) extension to work?  For example, it's included in the [hklpy `conf.py`](https://github.com/bluesky/hklpy/blob/a58f080ddd117e78f9a72661aaea94ee95fa7210/doc/source/conf.py#L43) but still there is no link to any of the source code.

This was added in https://github.com/bluesky/bluesky/issues/665 (and resolved as fixed in https://github.com/bluesky/bluesky/pull/666) yet links to the source code are still not shown.

**Pull request merged**
