### PR TITLE
TST: test against bluesky protocols

### PR DESCRIPTION
**Pull request by untzag**
Adding test which explicitly checks ophyd objects against new bluesky protocols using static analysis. I'm sure there are more objects that could be checked, willing to add if desired.

### CODE REVIEW

**Comment by untzag** [comment]
Passes locally, don't immediately understand why it doesn't pass in CI. Don't have time to think about it at the moment, will return.

**Comment by ksunden** [comment]
perhaps try putting the test file in a separate directory and running mypy from that directory?

**Comment by untzag** [comment]
Played around, the solution ended up being `--follow-imports=skip`. Don't know why I don't need that locally, but if it works it works :shrug:

This is ready for review I'm curious if y'all think this is a good idea.

I've been seeing some pytest failures which I don't think is related to this change.

**Comment by untzag** [comment]
Single TimeoutError for 3.6, believe it's unrelated.

This is ready for review again. Everything goes via pytest now :smile:

**Review by mrakitin — APPROVED** [review]
Looks good to me!

**Comment by mrakitin** [comment]
@tacaswell, @danielballan, any objections to merging it?

**Pull request merged**
