### PR TITLE
CLN: clean up dependencies left from ophyd v2

### PR DESCRIPTION
**Pull request by mrakitin**
As discussed in Slack with @coretl.

### CODE REVIEW

**Comment by mrakitin** [comment]
Done! I've removed the `v2/` directory and made some touch ups in the code/docs.

**Comment by mrakitin** [comment]
@coretl, it's ready for re-review!

**Review by coretl — APPROVED** [review]

**Comment by prjemian** [comment]
@mrakitin : Can this PR be merged?  It's approved.

**Comment by mrakitin** [comment]
I'll rebase and merge, thanks for the reminder, @prjemian!

**Comment by mrakitin** [comment]
Thanks, @tacaswell!

**Pull request merged**
