### PR TITLE
Make DeviceStatus report a fraction 0 rather than 1 once complete

### PR DESCRIPTION
**Pull request by callumforrester**
`MoveStatus` reports a `fraction` starting at 1 and tending towards 0 as the underlying operation progresses toward its goal. You would expect a `MoveStatus` to report a final fraction of 0, but instead it reports a 1. This is because it inherits from `DeviceStatus`, which reports a fraction of 1 as part of its `_settled` hook. 

One class treats `fraction` as "how far have we come?". The other treats it as "how far do we have to go?". This PR takes the behaviour of `MoveStatus` as canonical and modifies `DeviceStatus` in accordance.

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
I want eyes from another facility than NSLS-II on this before we merge.

**Comment by tacaswell** [comment]
This is a minor API change and I can imagine that it could surprise someone, I don't think we need everyone I tagged to sign off (and my choice of people was arbitrary), but we do need a to make sure everyone has a fair chance to object ;).

**Review by mrakitin — APPROVED** [review]

**Review by ZLLentz — APPROVED** [review]
This makes sense to me and will not break any LCLS code

**Review by prjemian — APPROVED** [review]
I do not foresee this causing any problems at APS.

**Review by untzag — APPROVED** [review]
Fine with me. Given that we were surprised by this inconsistency, is this a place where additional documentation and testing would serve us well? I can't see anywhere where we've written down the expected behavior of `fraction` (haven't looked too hard).

**Comment by tacaswell** [comment]
"power cycled" to pickup recent improvements to CI.

**Comment by tacaswell** [comment]
The failure looks real.  It may be a test that has landed on main from when the PR was opened (the tests run an the proposed merged commit not the tip of this branch).

**Comment by callumforrester** [comment]
@tacaswell Not sure why 3.7 would hang, would you mind rerunning?

**Comment by tacaswell** [comment]
Merged!  This may be the highest number of approvals per LoC changed we have had in ophyd yet.

**Pull request merged**
