### PR TITLE
TST: add a test to demonstrate MoveStatus._notify_watchers failure

### PR DESCRIPTION
**Pull request by mrakitin**
See #794 for the context.

### CODE REVIEW

**Comment by mrakitin** [comment]
The problem is reproduced via the test in this PR: https://travis-ci.com/mrakitin/ophyd/jobs/285017761#L3707.

Should it be merged first, and then a separate fix would solve it? Or is it better to do in one shot?

**Comment by prjemian** [comment]
One Clean Shot

**Comment by mrakitin** [comment]
Yeah, thanks for the suggestion, @prjemian. I thought it would make sense too, but having a future reference to the problem itself would be good too. Anyway, it's documented via #794.

**Comment by klauer** [comment]
👍 after fixing the `watch` callback signature issue.

**Comment by mrakitin** [comment]
41bba72 fixes the issue with formatting introduced in https://github.com/bluesky/ophyd/pull/790.

**Comment by mrakitin** [comment]
Thanks, @klauer!

**Pull request merged**
