### PR TITLE
DOC Describe init_pos kwarg

### PR DESCRIPTION
**Pull request by prjemian**
Motivated by https://github.com/bluesky/hklpy/issues/147

### CODE REVIEW

**Comment by prjemian** [comment]
Another good question is: Why is this kwarg named `init_pos` and not `value` like other classes, such as `Signal`?

**Review by tacaswell — APPROVED** [review]
modulo the docs getting fixed.

**Comment by tacaswell** [comment]
@prjemian The docs all still look broken?

**Comment by prjemian** [comment]
I don't see the new edit yet.  The publishing build failed here:

```python
make: Entering directory '/home/runner/work/ophyd/ophyd/docs'
sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v1.6.7
making output directory...

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 280, in setup
    app.add_css_file('plot_directive.css')
AttributeError: 'Sphinx' object has no attribute 'add_css_file'
The full traceback has been saved in /tmp/sphinx-err-hze40yz5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:61: html] Error 1
make: Leaving directory '/home/runner/work/ophyd/ophyd/docs'
Error: Process completed with exit code 2.
```

The Sphinx version is exceptionally old (most recent release is 4.0.0b or some such).  The change this PR contributed cannot be responsible for that problem.  This is a new bug then.

**Comment by mrakitin** [comment]
That's what I found regarding the `AttributeError: 'Sphinx' object has no attribute 'add_css_file'` error: https://github.com/sphinx-doc/sphinx/issues/7747#issuecomment-636023612. We should upgrade the sphinx version.

**Comment by mrakitin** [comment]
I did not realize we had that hard pin:
https://github.com/bluesky/ophyd/blob/82053af306815a4980aa4689a31d717f3234bd43/requirements-docs.txt#L6

Matplotlib extension seems to require the latest API.

**Comment by prjemian** [comment]
Please move comments to related issue #986

**Pull request merged**
