### PR TITLE
Update CI shield in README.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
Looks like:
image

**Comment by prjemian** [comment]
`ophyd - EPICS Client Abstractions`

Could this change to `ophyd - hardware client abstractions` (so not to exclude the non-EPICS world that must exist somewhere)

**Comment by danielballan** [comment]
Ah, I meant to do that while I was here. Thanks for the bump. Done.

**Comment by danielballan** [comment]
I'll that thumbs up from @prjemian as an approval and self-merge. Pushing to get all our major repos in good standing today....

**Pull request merged**
